/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-107243-gbeaf172d75-20220625"
#endif /* AVUTIL_FFVERSION_H */
